# Generated by Django 5.1.7 on 2025-03-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_auhor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhor',
            new_name='author',
        ),
    ]
